# Generated by Django 4.2.3 on 2023-07-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_primer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
